In [ ]:
import pandas as pd
from google.colab import files
from google.colab import drive
drive.mount('/content/drive')

url = ("/content/drive/MyDrive/Donnees_Projet2/tmdb_full.csv")
fichier_tmdb = pd.read_csv(url, sep=",", encoding='utf-8', header=0)

Mounted at /content/drive

<ipython-input-5-c8db36579f81>:7: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  fichier_tmdb = pd.read_csv(url, sep=",", encoding='utf-8', header=0)

In [ ]:
fichier_tmdb.shape

(309572, 25)

In [ ]:
fichier_tmdb.columns

Index(['adult', 'backdrop_path', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'video', 'vote_average', 'vote_count', 'production_companies_name',
       'production_companies_country'],
      dtype='object')

In [ ]:
fichier_tmdb.head(1)

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,production_companies_name,production_companies_country
0,False,/dvQj1GBZAZirz1skEEZyWH2ZqQP.jpg,0,['Comedy'],NaN,3924,tt0029927,en,Blondie,Blondie and Dagwood are about to celebrate the...,...,70,['en'],Released,The favorite comic strip of millions at last o...,Blondie,False,7.214,7,['Columbia Pictures'],['US']

In [ ]:
fichier_tmdb['imdb_id'].value_counts()

imdb_id
tt0029927     1
tt0814150     1
tt0111298     1
tt0093725     1
tt0027118     1
             ..
tt5884798     1
tt0167906     1
tt0435438     1
tt3467906     1
tt27688034    1
Name: count, Length: 309572, dtype: int64

In [ ]:
title_series = pd.read_csv("/content/drive/MyDrive/Donnees_Projet2/data_series_filtres.csv",
                            sep=',', encoding='utf-8', header=0)

In [ ]:
title_series.shape

(430048, 12)

In [ ]:
title_series.head(3)

,tconst,parentTconst,seasonNumber,episodeNumber,titleId_x,ordering,title_episode,region,language,type,titleId_y,title_series
0,tt0060556,tt0815352,1,21,tt0060556,2,"Jean Renoir le patron, 1e partie: La recherche...",FR,\N,\N,tt0815352,CinÃ©astes de notre temps
1,tt0066931,tt1466074,1,3,tt0066931,4,Poids mort,FR,\N,\N,tt1466074,Columbo
2,tt0066932,tt1466074,1,1,tt0066932,3,Le livre tÃ©moin,FR,\N,\N,tt1466074,Columbo

In [ ]:
title_series['parentTconst'].value_counts()

parentTconst
tt0044265     17864
tt0058796     14955
tt0069658     12801
tt0053494     10880
tt0048845     10700
              ...
tt10290478        1
tt13207736        1
tt8656736         1
tt30495117        1
tt0985074         1
Name: count, Length: 6254, dtype: int64

In [ ]:
series_finals = fichier_tmdb.merge(title_series, how='outer', left_on='original_title', right_on='title_series')

In [ ]:
series_finals.shape

(814836, 37)

In [ ]:
series_finals.head(5)

,adult,backdrop_path,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,seasonNumber,episodeNumber,titleId_x,ordering,title_episode,region,language,type,titleId_y,title_series
0,False,/9yHD9ZYkJke20JPnRLFhj2MG7D0.jpg,0.0,['Documentary'],http://www.womenartrevolution.com/,55245.0,tt1699720,en,!Women Art Revolution,"Through intimate interviews, provocative art, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,False,NaN,0.0,[],NaN,433173.0,tt0277541,en,"""..."" Reel 3","In 1998, Brakhage completed the five reels of ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,False,NaN,0.0,[],NaN,547829.0,tt0277539,en,"""..."" Reel 4","This work is in five reels (numbered, but call...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,False,NaN,0.0,[],NaN,163360.0,tt0225002,en,"""..."" Reel Five",Reel #5 of (...) is composed of scratch-imager...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,False,/fcK176zCHCAeTVnMVVmip2HMoAX.jpg,0.0,"['Documentary', 'Adventure']",NaN,564096.0,tt9536804,en,"""BLESSED""","Supreme presents, ""BLESSED"" a full length vide...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
series_finals.columns

Index(['tconst', 'parentTconst', 'genres', 'seasonNumber', 'episodeNumber',
       'title_episode', 'title_series', 'ordering', 'budget', 'revenue',
       'production_countries', 'homepage', 'imdb_id', 'overview', 'popularity',
       'poster_path', 'release_date'],
      dtype='object')

In [ ]:
series_finals['release_date'].value_counts()

release_date
2011-11-01    6166
2022-02-16    6143
1972-04-22    6125
2020-11-18    4689
1960-11-24    4661
              ...
1970-01-27       1
1941-04-06       1
1951-03-20       1
1915-08-17       1
1967-07-30       1
Name: count, Length: 37575, dtype: int64

In [ ]:
col_finales = ['tconst', 'parentTconst', 'genres', 'seasonNumber', 'episodeNumber', 'title_episode', 'title_series', 'ordering', 'budget','revenue','production_countries','homepage','imdb_id', 'overview', 'popularity', 'poster_path', 'release_date']

series_finals= series_finals[col_finales]

In [ ]:
series_finals.shape

(814836, 17)

In [ ]:
series_finals.head()

,tconst,parentTconst,genres,seasonNumber,episodeNumber,title_episode,title_series,ordering,budget,revenue,production_countries,homepage,imdb_id,overview,popularity,poster_path,release_date
0,NaN,NaN,['Documentary'],NaN,NaN,NaN,NaN,NaN,0.0,0.0,[],http://www.womenartrevolution.com/,tt1699720,"Through intimate interviews, provocative art, ...",0.600,/bUfLZKgGUXQMZLI7d9tUlT1Vdt9.jpg,2010-09-12
1,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,0.0,0.0,[],NaN,tt0277541,"In 1998, Brakhage completed the five reels of ...",1.091,/oxrhorDQM0TtQdPxqz4saSHK1GT.jpg,1998-01-04
2,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,0.0,0.0,['US'],NaN,tt0277539,"This work is in five reels (numbered, but call...",0.600,/exUr63YO2jarpXqzBCg5aortgGt.jpg,1998-01-01
3,NaN,NaN,[],NaN,NaN,NaN,NaN,NaN,0.0,0.0,['US'],NaN,tt0225002,Reel #5 of (...) is composed of scratch-imager...,0.990,/1rr9izT7Q92FFl5iFPBSH8Q3S3w.jpg,1998-01-01
4,NaN,NaN,"['Documentary', 'Adventure']",NaN,NaN,NaN,NaN,NaN,0.0,0.0,['US'],NaN,tt9536804,"Supreme presents, ""BLESSED"" a full length vide...",1.542,/me0Y4KYmHFwtWjPxQwlF8GjyPkQ.jpg,2018-11-22

In [ ]:
series_finals['release_date'].value_counts()

release_date
2011-11-01    6166
2022-02-16    6143
1972-04-22    6125
2020-11-18    4689
1960-11-24    4661
              ...
1970-01-27       1
1941-04-06       1
1951-03-20       1
1915-08-17       1
1967-07-30       1
Name: count, Length: 37575, dtype: int64

In [ ]:
series_finals["parentTconst"].isna().sum()

307384

In [ ]:
series_finals.shape

(814836, 17)

In [ ]:
series_finals["release_date"]=pd.to_datetime(series_finals["release_date"])

In [ ]:
series_finals["release_date"].dt.year>=1960
series_finals=series_finals[series_finals["release_date"].dt.year>=1960]

In [ ]:
series_finals.shape

(366432, 17)

In [ ]:
series_finals = series_finals.dropna(subset=["parentTconst"])

In [ ]:
series_finals

,tconst,parentTconst,genres,seasonNumber,episodeNumber,title_episode,title_series,ordering,budget,revenue,production_countries,homepage,imdb_id,overview,popularity,poster_path,release_date
1280,tt0971226,tt0905574,"['Animation', 'Drama', 'Fantasy']",1.0,1.0,Ã‰pisode #1.1,1001 Nights,4.0,0.0,0.0,"['US', 'JP']",NaN,tt0193688,Presented in the form of a feverish love dream...,1.951,/3gl8VY6dFoWYAwwcyhFnKTT3d1b.jpg,1998-04-30
1281,tt0971227,tt0905574,"['Animation', 'Drama', 'Fantasy']",1.0,10.0,Ã‰pisode #1.10,1001 Nights,4.0,0.0,0.0,"['US', 'JP']",NaN,tt0193688,Presented in the form of a feverish love dream...,1.951,/3gl8VY6dFoWYAwwcyhFnKTT3d1b.jpg,1998-04-30
1282,tt0971228,tt0905574,"['Animation', 'Drama', 'Fantasy']",1.0,11.0,Ã‰pisode #1.11,1001 Nights,4.0,0.0,0.0,"['US', 'JP']",NaN,tt0193688,Presented in the form of a feverish love dream...,1.951,/3gl8VY6dFoWYAwwcyhFnKTT3d1b.jpg,1998-04-30
1283,tt0971229,tt0905574,"['Animation', 'Drama', 'Fantasy']",1.0,12.0,Ã‰pisode #1.12,1001 Nights,4.0,0.0,0.0,"['US', 'JP']",NaN,tt0193688,Presented in the form of a feverish love dream...,1.951,/3gl8VY6dFoWYAwwcyhFnKTT3d1b.jpg,1998-04-30
1284,tt0971230,tt0905574,"['Animation', 'Drama', 'Fantasy']",1.0,13.0,Ã‰pisode #1.13,1001 Nights,4.0,0.0,0.0,"['US', 'JP']",NaN,tt0193688,Presented in the form of a feverish love dream...,1.951,/3gl8VY6dFoWYAwwcyhFnKTT3d1b.jpg,1998-04-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771654,tt27634206,tt27613329,"['Fantasy', 'Mystery', 'Romance', 'Thriller']",2.0,4.0,Ã‰pisode #2.4,Ã‰toile,4.0,0.0,0.0,['IT'],NaN,tt0096522,An American ballerina arrives in Hungary to en...,4.234,/AgezMjwwGt9bgSagC64W6C4o4xs.jpg,1989-03-17
771655,tt27634207,tt27613329,"['Fantasy', 'Mystery', 'Romance', 'Thriller']",2.0,3.0,Ã‰pisode #2.3,Ã‰toile,4.0,0.0,0.0,['IT'],NaN,tt0096522,An American ballerina arrives in Hungary to en...,4.234,/AgezMjwwGt9bgSagC64W6C4o4xs.jpg,1989-03-17
771656,tt27634208,tt27613329,"['Fantasy', 'Mystery', 'Romance', 'Thriller']",2.0,6.0,Ã‰pisode #2.6,Ã‰toile,4.0,0.0,0.0,['IT'],NaN,tt0096522,An American ballerina arrives in Hungary to en...,4.234,/AgezMjwwGt9bgSagC64W6C4o4xs.jpg,1989-03-17
771657,tt27634209,tt27613329,"['Fantasy', 'Mystery', 'Romance', 'Thriller']",2.0,8.0,Ã‰pisode #2.8,Ã‰toile,4.0,0.0,0.0,['IT'],NaN,tt0096522,An American ballerina arrives in Hungary to en...,4.234,/AgezMjwwGt9bgSagC64W6C4o4xs.jpg,1989-03-17
771658,tt27634210,tt27613329,"['Fantasy', 'Mystery', 'Romance', 'Thriller']",2.0,7.0,Ã‰pisode #2.7,Ã‰toile,4.0,0.0,0.0,['IT'],NaN,tt0096522,An American ballerina arrives in Hungary to en...,4.234,/AgezMjwwGt9bgSagC64W6C4o4xs.jpg,1989-03-17

In [ ]:
series_finals['title_series'].value_counts()

NameError: name 'series_finals' is not defined

In [ ]:
#series_finals.to_csv('/content/drive/MyDrive/Donnees_Projet2/series_finals.csv', index=False)

In [ ]:
import requests
import zipfile
import pandas as pd

url = "https://raw.githubusercontent.com/PikaChou82/Magma_Analytics/refs/heads/main/Datasets/df_series_finales.zip"
response = requests.get(url)
open('df_series_finales.zip', 'wb').write(response.content)

1345444

In [ ]:
with zipfile.ZipFile('df_series_finales.zip', 'r') as zip_ref:
    zip_ref.extractall('temp')

In [ ]:
df = pd.read_csv('temp/df_series_finales.csv')

In [ ]:
df

,backdrop_path,overview,poster_path,original_language,vote_average,origin_country,parentTconst,tconst,seasonNumber,episodeNumber,ordering,title_episode,title_series,genres,startYear,episodeNumber\t
0,/zVnbHIJLT5myh9q8vBVNz7d7Qgg.jpg,The Carol Burnett Show is an American variety/...,/dGd9pG4PGzpJbdbPEnFxKrJ24z8.jpg,en,7.543,['US'],tt0061240,tt0536546,1,1,4,Ã‰pisode #1.1,The Carol Burnett Show,Comedy,1967,1
1,/zVnbHIJLT5myh9q8vBVNz7d7Qgg.jpg,The Carol Burnett Show is an American variety/...,/dGd9pG4PGzpJbdbPEnFxKrJ24z8.jpg,en,7.543,['US'],tt0061240,tt1787554,5,24,4,Ã‰pisode #5.24,The Carol Burnett Show,Comedy,1967,24
2,/zVnbHIJLT5myh9q8vBVNz7d7Qgg.jpg,The Carol Burnett Show is an American variety/...,/dGd9pG4PGzpJbdbPEnFxKrJ24z8.jpg,en,7.543,['US'],tt0061240,tt1789575,11,3,4,Ã‰pisode #11.3,The Carol Burnett Show,Comedy,1967,3
3,/zVnbHIJLT5myh9q8vBVNz7d7Qgg.jpg,The Carol Burnett Show is an American variety/...,/dGd9pG4PGzpJbdbPEnFxKrJ24z8.jpg,en,7.543,['US'],tt0061240,tt1801381,11,5,4,Ã‰pisode #11.5,The Carol Burnett Show,Comedy,1967,5
4,NaN,One Life to Live is an American soap opera bro...,/rolhu6G57XutH95hcsgMPDTtviw.jpg,en,7.417,['US'],tt0062595,tt0665949,1,5742,4,Ã‰pisode #1.5742,On ne vit qu'une fois,Soap,1968,5742
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60753,/swDg4wkwLzmXHdxfymLZXUNiFcB.jpg,NaN,/80GrjkbOiigGdOtsGrFroj3Q14w.jpg,tr,7.082,['TR'],tt9915022,tt11344062,1,164,4,Ã‰pisode #1.164,Yarali Kuslar,Drama,2019,164
60754,/swDg4wkwLzmXHdxfymLZXUNiFcB.jpg,NaN,/80GrjkbOiigGdOtsGrFroj3Q14w.jpg,tr,7.082,['TR'],tt9915022,tt11344066,1,165,4,Ã‰pisode #1.165,Yarali Kuslar,Drama,2019,165
60755,/w9QhOrUWfJ0EnHPMgf0pKvx2u3d.jpg,NaN,/eWoOjNDPkU7Zwakobp4nNyEOOvw.jpg,fr,7.000,"['DE', 'FR']",tt9915880,tt10747014,1,7,2,L'ortie,Chroniques VÃ©gÃ©tales,Documentary,2019,7
60756,/w9QhOrUWfJ0EnHPMgf0pKvx2u3d.jpg,NaN,/eWoOjNDPkU7Zwakobp4nNyEOOvw.jpg,fr,7.000,"['DE', 'FR']",tt9915880,tt10747060,1,9,2,L'achillÃ©e millefeuille,Chroniques VÃ©gÃ©tales,Documentary,2019,9
60757,/w9QhOrUWfJ0EnHPMgf0pKvx2u3d.jpg,NaN,/eWoOjNDPkU7Zwakobp4nNyEOOvw.jpg,fr,7.000,"['DE', 'FR']",tt9915880,tt10747078,1,10,2,La bourrache officinale,Chroniques VÃ©gÃ©tales,Documentary,2019,10

In [ ]:
df['title_series'].nunique()

2030

In [ ]:
df.to_csv('/content/drive/MyDrive/Donnees_Projet2/df_series_finals_new.csv', index=False)

In [ ]:
df['startYear'].value_counts()

startYear
2015    4296
1968    4202
2021    3785
2020    3674
2017    3385
        ...
1982      11
1970       6
1962       6
1976       5
1975       4
Name: count, Length: 61, dtype: int64

In [ ]:
# Suppression des doublons et sample ensuite sur 200 series
liste_serie =df['parentTconst'].drop_duplicates().sample(n=200)
df =df[df['parentTconst'].isin(liste_serie)]

In [ ]:
df

,backdrop_path,overview,poster_path,original_language,vote_average,origin_country,parentTconst,tconst,seasonNumber,episodeNumber,ordering,title_episode,title_series,genres,startYear,episodeNumber\t
5721,/tSpREAMP0HqPZqAKG4ubr4xPDPy.jpg,A young woman whose childhood was so harrowing...,/rQxfLUaZ67vS1bBxR9hqDGOJwqA.jpg,en,7.400,['US'],tt0075296,tt3990650,1,1,4,Ã‰pisode #1.1,Sybil,Drama,1976,1
5722,/tSpREAMP0HqPZqAKG4ubr4xPDPy.jpg,A young woman whose childhood was so harrowing...,/rQxfLUaZ67vS1bBxR9hqDGOJwqA.jpg,en,7.400,['US'],tt0075296,tt3990652,1,2,4,Ã‰pisode #1.2,Sybil,Drama,1976,2
6503,/j5hn3Xn2BDbwR3tBX7s8m8Y1zce.jpg,An English navigator becomes both a player and...,/vfcbFozvKkC2dRqsNn0soIHGfBL.jpg,en,7.642,['US'],tt0080274,tt1484292,1,4,4,Ã‰pisode #1.4,Shogun,Action & Adventure,1980,4
6504,/j5hn3Xn2BDbwR3tBX7s8m8Y1zce.jpg,An English navigator becomes both a player and...,/vfcbFozvKkC2dRqsNn0soIHGfBL.jpg,en,7.642,['US'],tt0080274,tt1488968,1,1,4,Ã‰pisode #1.1,Shogun,Action & Adventure,1980,1
6505,/j5hn3Xn2BDbwR3tBX7s8m8Y1zce.jpg,An English navigator becomes both a player and...,/vfcbFozvKkC2dRqsNn0soIHGfBL.jpg,en,7.642,['US'],tt0080274,tt1488969,1,2,4,Ã‰pisode #1.2,Shogun,Action & Adventure,1980,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60515,/COVrHeFLXlk7MDxWXmsNg7wAOh.jpg,What happens when you return from a family hol...,/bxrVYJLPRxJkTYVfo24bq7cfI8m.jpg,en,7.000,['GB'],tt9883888,tt9889944,1,5,4,Ã‰pisode #1.5,Home,Comedy,2019,5
60516,/COVrHeFLXlk7MDxWXmsNg7wAOh.jpg,What happens when you return from a family hol...,/bxrVYJLPRxJkTYVfo24bq7cfI8m.jpg,en,7.000,['GB'],tt9883888,tt9889946,1,6,4,Ã‰pisode #1.6,Home,Comedy,2019,6
60569,/tM25DV1252RaOVfktNWRs7rZx60.jpg,"An art curator's life unravels, as she tries t...",/nr4BB5JoTyxrtaNVMECinuMzTMA.jpg,ko,7.703,['KR'],tt9899340,tt10196710,1,6,4,Ã‰pisode #1.6,Geunyeoui Sasaenghwal,Comedy,2019,6
60570,/tM25DV1252RaOVfktNWRs7rZx60.jpg,"An art curator's life unravels, as she tries t...",/nr4BB5JoTyxrtaNVMECinuMzTMA.jpg,ko,7.703,['KR'],tt9899340,tt10196716,1,7,4,Ã‰pisode #1.7,Geunyeoui Sasaenghwal,Comedy,2019,7
60571,/tM25DV1252RaOVfktNWRs7rZx60.jpg,"An art curator's life unravels, as she tries t...",/nr4BB5JoTyxrtaNVMECinuMzTMA.jpg,ko,7.703,['KR'],tt9899340,tt10196724,1,9,4,Ã‰pisode #1.9,Geunyeoui Sasaenghwal,Comedy,2019,9

In [ ]:
#df = df.dropna()
#df

,backdrop_path,overview,poster_path,original_language,vote_average,origin_country,parentTconst,tconst,seasonNumber,episodeNumber,ordering,title_episode,title_series,genres,startYear,episodeNumber\t
4609,/vxU0KCOd3ykY2AbC2RxXckO9u6F.jpg,Italian miniseries based on Homer's Odyssey.,/4iBgeghJz97TjQK9CUPyD8kz8K3.jpg,it,8.9,['IT'],tt0064750,tt2414334,1,1,4,Ã‰pisode #1.1,L'odyssÃ©e,Drama,1968,1
4610,/vxU0KCOd3ykY2AbC2RxXckO9u6F.jpg,Italian miniseries based on Homer's Odyssey.,/4iBgeghJz97TjQK9CUPyD8kz8K3.jpg,it,8.9,['IT'],tt0064750,tt2418978,1,2,4,Ã‰pisode #1.2,L'odyssÃ©e,Drama,1968,2
4611,/vxU0KCOd3ykY2AbC2RxXckO9u6F.jpg,Italian miniseries based on Homer's Odyssey.,/4iBgeghJz97TjQK9CUPyD8kz8K3.jpg,it,8.9,['IT'],tt0064750,tt2419930,1,3,4,Ã‰pisode #1.3,L'odyssÃ©e,Drama,1968,3
4612,/vxU0KCOd3ykY2AbC2RxXckO9u6F.jpg,Italian miniseries based on Homer's Odyssey.,/4iBgeghJz97TjQK9CUPyD8kz8K3.jpg,it,8.9,['IT'],tt0064750,tt2419936,1,4,4,Ã‰pisode #1.4,L'odyssÃ©e,Drama,1968,4
4613,/vxU0KCOd3ykY2AbC2RxXckO9u6F.jpg,Italian miniseries based on Homer's Odyssey.,/4iBgeghJz97TjQK9CUPyD8kz8K3.jpg,it,8.9,['IT'],tt0064750,tt2419960,1,5,4,Ã‰pisode #1.5,L'odyssÃ©e,Drama,1968,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60564,/2SR7rnQDnuQ1vhQ68acNGJVRCPE.jpg,"With graduation 10 days away, homeroom teacher...",/nzEJMNAWj1HO8yM62tlZD5pmeiV.jpg,ja,8.0,['JP'],tt9899068,tt10333580,1,6,4,Ã‰pisode #1.6,Mr. Hiiragi's Homeroom,Crime,2019,6
60565,/2SR7rnQDnuQ1vhQ68acNGJVRCPE.jpg,"With graduation 10 days away, homeroom teacher...",/nzEJMNAWj1HO8yM62tlZD5pmeiV.jpg,ja,8.0,['JP'],tt9899068,tt10333582,1,7,4,Ã‰pisode #1.7,Mr. Hiiragi's Homeroom,Crime,2019,7
60566,/2SR7rnQDnuQ1vhQ68acNGJVRCPE.jpg,"With graduation 10 days away, homeroom teacher...",/nzEJMNAWj1HO8yM62tlZD5pmeiV.jpg,ja,8.0,['JP'],tt9899068,tt10333584,1,8,4,Ã‰pisode #1.8,Mr. Hiiragi's Homeroom,Crime,2019,8
60567,/2SR7rnQDnuQ1vhQ68acNGJVRCPE.jpg,"With graduation 10 days away, homeroom teacher...",/nzEJMNAWj1HO8yM62tlZD5pmeiV.jpg,ja,8.0,['JP'],tt9899068,tt10333586,1,9,4,Ã‰pisode #1.9,Mr. Hiiragi's Homeroom,Crime,2019,9
60568,/2SR7rnQDnuQ1vhQ68acNGJVRCPE.jpg,"With graduation 10 days away, homeroom teacher...",/nzEJMNAWj1HO8yM62tlZD5pmeiV.jpg,ja,8.0,['JP'],tt9899068,tt10333590,1,10,4,Ã‰pisode #1.10,Mr. Hiiragi's Homeroom,Crime,2019,10

In [ ]:
df['genres'].value_counts()

genres
Drama                 3104
Action & Adventure     788
Comedy                 445
Crime                  426
Kids                   186
Animation              135
Sci-Fi & Fantasy       113
Documentary             86
Family                  69
Mystery                 36
War & Politics          20
Soap                     1
Name: count, dtype: int64

In [ ]:
# CrÃ©ation d'un df excluant les colonnes (seasonNumber,	episodeNumber, episodeNumber\t, 'title_episode','tconst')
colonnes_filtrees = ['backdrop_path',	'overview',	'poster_path',	'original_language',	'vote_average',	'origin_country',	'parentTconst', 'ordering',		'title_series',	'genres',	'startYear']

df_filtre = df[colonnes_filtrees]
df_filtre

,backdrop_path,overview,poster_path,original_language,vote_average,origin_country,parentTconst,ordering,title_series,genres,startYear
5721,/tSpREAMP0HqPZqAKG4ubr4xPDPy.jpg,A young woman whose childhood was so harrowing...,/rQxfLUaZ67vS1bBxR9hqDGOJwqA.jpg,en,7.400,['US'],tt0075296,4,Sybil,Drama,1976
5722,/tSpREAMP0HqPZqAKG4ubr4xPDPy.jpg,A young woman whose childhood was so harrowing...,/rQxfLUaZ67vS1bBxR9hqDGOJwqA.jpg,en,7.400,['US'],tt0075296,4,Sybil,Drama,1976
6503,/j5hn3Xn2BDbwR3tBX7s8m8Y1zce.jpg,An English navigator becomes both a player and...,/vfcbFozvKkC2dRqsNn0soIHGfBL.jpg,en,7.642,['US'],tt0080274,4,Shogun,Action & Adventure,1980
6504,/j5hn3Xn2BDbwR3tBX7s8m8Y1zce.jpg,An English navigator becomes both a player and...,/vfcbFozvKkC2dRqsNn0soIHGfBL.jpg,en,7.642,['US'],tt0080274,4,Shogun,Action & Adventure,1980
6505,/j5hn3Xn2BDbwR3tBX7s8m8Y1zce.jpg,An English navigator becomes both a player and...,/vfcbFozvKkC2dRqsNn0soIHGfBL.jpg,en,7.642,['US'],tt0080274,4,Shogun,Action & Adventure,1980
...,...,...,...,...,...,...,...,...,...,...,...
60515,/COVrHeFLXlk7MDxWXmsNg7wAOh.jpg,What happens when you return from a family hol...,/bxrVYJLPRxJkTYVfo24bq7cfI8m.jpg,en,7.000,['GB'],tt9883888,4,Home,Comedy,2019
60516,/COVrHeFLXlk7MDxWXmsNg7wAOh.jpg,What happens when you return from a family hol...,/bxrVYJLPRxJkTYVfo24bq7cfI8m.jpg,en,7.000,['GB'],tt9883888,4,Home,Comedy,2019
60569,/tM25DV1252RaOVfktNWRs7rZx60.jpg,"An art curator's life unravels, as she tries t...",/nr4BB5JoTyxrtaNVMECinuMzTMA.jpg,ko,7.703,['KR'],tt9899340,4,Geunyeoui Sasaenghwal,Comedy,2019
60570,/tM25DV1252RaOVfktNWRs7rZx60.jpg,"An art curator's life unravels, as she tries t...",/nr4BB5JoTyxrtaNVMECinuMzTMA.jpg,ko,7.703,['KR'],tt9899340,4,Geunyeoui Sasaenghwal,Comedy,2019
60571,/tM25DV1252RaOVfktNWRs7rZx60.jpg,"An art curator's life unravels, as she tries t...",/nr4BB5JoTyxrtaNVMECinuMzTMA.jpg,ko,7.703,['KR'],tt9899340,4,Geunyeoui Sasaenghwal,Comedy,2019

In [ ]:
df_filtre = df_filtre.drop_duplicates()
df_filtre = df_filtre.reset_index()

In [ ]:
import pandas as pd
url_serie = "https://raw.githubusercontent.com/PikaChou82/Magma_Analytics/refs/heads/main/Datasets/df_definitif_series.csv"
df = pd.read_csv(url_serie, sep=',', encoding='utf-8')

In [ ]:
df

,index,backdrop_path,overview,poster_path,original_language,vote_average,origin_country,parentTconst,title_series,genres,startYear
0,0,/pgnyWjaCMgPuHSav7ejQcY9Vfsg.jpg,"Balsamo, a scoundrel with the gift of mesmeris...",/zbQwYWG6b96YOm9AnjxCmutZU6v.jpg,fr,7.000,['FR'],tt0069570,Joseph Balsamo,Drama,1973.0
1,4,/j5hn3Xn2BDbwR3tBX7s8m8Y1zce.jpg,An English navigator becomes both a player and...,/vfcbFozvKkC2dRqsNn0soIHGfBL.jpg,en,7.642,['US'],tt0080274,Shogun,Action & Adventure,1980.0
2,9,/i8ZIhsRmHORpVzx5fLa52WoAuNi.jpg,"Set against the brutal chaos of World War II, ...",/kJcNzMyTxbURhccLbqSNF0EUUZe.jpg,en,7.600,['AU'],tt0081949,A Town Like Alice,Drama,1981.0
3,12,/4Ma7OxeciQAzw5HZ0QxoabI0bIs.jpg,"Kane & Abel is a television miniseries, based ...",/msBIc6YXux5HXA9u5O7oQZZnlol.jpg,en,7.400,['US'],tt0088547,Le pouvoir et la gloire,Drama,1985.0
4,15,/8dgnA9Ac9M50KjABzQOiwYPXvMr.jpg,"Tracy Whitney was in love, pregnant and engage...",/4ooPNtGVZ4w72rJyDrFl2qySezm.jpg,en,7.200,['US'],tt0090455,Les diamants de la vengeance,Crime,1986.0
...,...,...,...,...,...,...,...,...,...,...,...
205,6505,/qaBwj91q7bx21y4xFAAYHR7wrDL.jpg,"Down deep in the Mississippi Delta, Trap music...",/qAuKjGNbcwdhbpxSciak8BFjQ5F.jpg,en,7.700,['US'],tt9340526,P-Valley,Drama,2020.0
206,6515,/i9IEOD1Li1y89xRHKH9kiE8dt9z.jpg,Earth is visited by an alien species that thre...,/wWFs3pl9gWHYvDElQVB4CB809m9.jpg,en,7.180,['US'],tt9737326,Invasion,Sci-Fi & Fantasy,2021.0
207,6516,/3fTEB9x8bxAQ055ecodeqLbMoLJ.jpg,A classical singer Radhe falls in love with po...,/kBzGbQYEfv8Wbdh60ND9V9dJt0S.jpg,hi,7.600,['IN'],tt9814458,Bandish Bandits,Family,2020.0
208,6517,/tM25DV1252RaOVfktNWRs7rZx60.jpg,"An art curator's life unravels, as she tries t...",/nr4BB5JoTyxrtaNVMECinuMzTMA.jpg,ko,7.703,['KR'],tt9899340,Geunyeoui Sasaenghwal,Comedy,2019.0
209,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**PCA ou KNN ...??**

In [58]:
# On ne garde que les titres
df =df.loc[:,['backdrop_path', 'overview', 'poster_path', 'original_language','vote_average', 'origin_country', 'parentTconst', 'title_series','genres', 'startYear']]
df = df.drop_duplicates()
df = df.reset_index()

In [59]:
from sklearn.decomposition import PCA
from sklearn.metrics import pairwise_distances
from sklearn.neighbors import NearestNeighbors
# Import des librairies

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy import stats
import folium
from sklearn.model_selection import learning_curve
import missingno as msno
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.preprocessing import RobustScaler

def reco_knn(df_filtre):
    # SÃ©lection des colonnes numÃ©riques pertinentes pour la recommandation
    df_filtre['genres_'] = df_filtre['genres'].factorize()[0]
    colonnes_numeriques = ['vote_average', 'startYear', 'genres_']
    df_numerique = df_filtre[colonnes_numeriques].dropna()  # Supprimer les lignes contenant des NaN

    # Normalisation des donnÃ©es
    df_numerique_normalized = (df_numerique - df_numerique.mean()) / df_numerique.std()

    """ MÃ©thode KNN """
    knn = NearestNeighbors(n_neighbors=4, metric='euclidean')  # 3 voisins et la serie elle mÃªme Ã  exclure
    knn.fit(df_numerique_normalized)

    # Trouvons les indices des voisins
    distances, indices = knn.kneighbors(df_numerique_normalized)

    # Ajouter les sÃ©ries similaires dans le DataFrame
    for i, voisin_indices in enumerate(indices):
        df_filtre.loc[i, 'voisin1'] = df_filtre.iloc[voisin_indices[0]]['title_series']
        df_filtre.loc[i, 'voisin2'] = df_filtre.iloc[voisin_indices[1]]['title_series']
        df_filtre.loc[i, 'voisin3'] = df_filtre.iloc[voisin_indices[2]]['title_series']
        df_filtre.loc[i, 'voisin4'] = df_filtre.iloc[voisin_indices[3]]['title_series']

    return df_filtre

# Ajoutons la fonction recommandations au df filtrÃ©
df_filtre_reco = reco_knn(df)

In [60]:
df_filtre_reco

,index,backdrop_path,overview,poster_path,original_language,vote_average,origin_country,parentTconst,title_series,genres,startYear,genres_,voisin1,voisin2,voisin3,voisin4
0,0,/pgnyWjaCMgPuHSav7ejQcY9Vfsg.jpg,"Balsamo, a scoundrel with the gift of mesmeris...",/zbQwYWG6b96YOm9AnjxCmutZU6v.jpg,fr,7.000,['FR'],tt0069570,Joseph Balsamo,Drama,1973.0,0,Joseph Balsamo,A Town Like Alice,Shogun,Le pouvoir et la gloire
1,1,/j5hn3Xn2BDbwR3tBX7s8m8Y1zce.jpg,An English navigator becomes both a player and...,/vfcbFozvKkC2dRqsNn0soIHGfBL.jpg,en,7.642,['US'],tt0080274,Shogun,Action & Adventure,1980.0,1,Shogun,A Town Like Alice,Le pouvoir et la gloire,Les diamants de la vengeance
2,2,/i8ZIhsRmHORpVzx5fLa52WoAuNi.jpg,"Set against the brutal chaos of World War II, ...",/kJcNzMyTxbURhccLbqSNF0EUUZe.jpg,en,7.600,['AU'],tt0081949,A Town Like Alice,Drama,1981.0,0,A Town Like Alice,Shogun,Le pouvoir et la gloire,Les diamants de la vengeance
3,3,/4Ma7OxeciQAzw5HZ0QxoabI0bIs.jpg,"Kane & Abel is a television miniseries, based ...",/msBIc6YXux5HXA9u5O7oQZZnlol.jpg,en,7.400,['US'],tt0088547,Le pouvoir et la gloire,Drama,1985.0,0,Le pouvoir et la gloire,A Town Like Alice,Shogun,Les diamants de la vengeance
4,4,/8dgnA9Ac9M50KjABzQOiwYPXvMr.jpg,"Tracy Whitney was in love, pregnant and engage...",/4ooPNtGVZ4w72rJyDrFl2qySezm.jpg,en,7.200,['US'],tt0090455,Les diamants de la vengeance,Crime,1986.0,2,Les diamants de la vengeance,Si c'Ã©tait demain,Sophie et Virginie,Le pouvoir et la gloire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,205,/qaBwj91q7bx21y4xFAAYHR7wrDL.jpg,"Down deep in the Mississippi Delta, Trap music...",/qAuKjGNbcwdhbpxSciak8BFjQ5F.jpg,en,7.700,['US'],tt9340526,P-Valley,Drama,2020.0,0,P-Valley,Law School,Kazara Ask,Mellangkollia
206,206,/i9IEOD1Li1y89xRHKH9kiE8dt9z.jpg,Earth is visited by an alien species that thre...,/wWFs3pl9gWHYvDElQVB4CB809m9.jpg,en,7.180,['US'],tt9737326,Invasion,Sci-Fi & Fantasy,2021.0,8,Invasion,The School Nurse Files,ÃœÃ§ Kiz Kardes,The Search for WondLa
207,207,/3fTEB9x8bxAQ055ecodeqLbMoLJ.jpg,A classical singer Radhe falls in love with po...,/kBzGbQYEfv8Wbdh60ND9V9dJt0S.jpg,hi,7.600,['IN'],tt9814458,Bandish Bandits,Family,2020.0,9,Bandish Bandits,ÃœÃ§ Kiz Kardes,The School Nurse Files,The Time Traveler's Wife
208,208,/tM25DV1252RaOVfktNWRs7rZx60.jpg,"An art curator's life unravels, as she tries t...",/nr4BB5JoTyxrtaNVMECinuMzTMA.jpg,ko,7.703,['KR'],tt9899340,Geunyeoui Sasaenghwal,Comedy,2019.0,5,Geunyeoui Sasaenghwal,Harlem,Family Matter,Tyler Perry's Young Dylan
209,209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,NaN,NaN

In [61]:
df_filtre_reco = df_filtre_reco.dropna()

In [62]:
df_filtre_reco.info()

<class 'pandas.core.frame.DataFrame'>
Index: 179 entries, 0 to 208
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              179 non-null    int64
 1   backdrop_path      179 non-null    object
 2   overview           179 non-null    object
 3   poster_path        179 non-null    object
 4   original_language  179 non-null    object
 5   vote_average       179 non-null    float64
 6   origin_country     179 non-null    object
 7   parentTconst       179 non-null    object
 8   title_series       179 non-null    object
 9   genres             179 non-null    object
 10  startYear          179 non-null    float64
 11  genres_            179 non-null    int64
 12  voisin1            179 non-null    object
 13  voisin2            179 non-null    object
 14  voisin3            179 non-null    object
 15  voisin4            179 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 23.8+ KB

In [ ]:
df_filtre_reco.columns

Index(['backdrop_path', 'overview', 'poster_path', 'original_language',
       'vote_average', 'origin_country', 'parentTconst', 'tconst',
       'seasonNumber', 'episodeNumber', 'ordering', 'title_episode',
       'title_series', 'genres', 'startYear', 'episodeNumber\t', 'voisin1',
       'voisin2', 'voisin3', 'voisin4'],
      dtype='object')

In [ ]:
df_filtre_reco.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 43
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   backdrop_path      8 non-null      object
 1   overview           8 non-null      object
 2   poster_path        8 non-null      object
 3   original_language  8 non-null      object
 4   vote_average       8 non-null      float64
 5   origin_country     8 non-null      object
 6   parentTconst       8 non-null      object
 7   title_series       8 non-null      object
 8   genres             8 non-null      object
 9   startYear          8 non-null      float64
 10  voisin1            8 non-null      object
 11  voisin2            8 non-null      object
 12  voisin3            8 non-null      object
 13  voisin4            8 non-null      object
dtypes: float64(2), object(12)
memory usage: 960.0+ bytes

In [64]:
df_filtre_reco.to_csv('df_reco_series_final.csv', index=False)

In [ ]:
url_reco = "https://raw.githubusercontent.com/PikaChou82/Magma_Analytics/refs/heads/main/Datasets/df_reco_series.csv"

dataset_reco = pd.read_csv(url_reco, sep=',', encoding='utf-8')
dataset_reco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              193 non-null    int64
 1   backdrop_path      193 non-null    object
 2   overview           193 non-null    object
 3   poster_path        193 non-null    object
 4   original_language  193 non-null    object
 5   vote_average       193 non-null    float64
 6   origin_country     193 non-null    object
 7   parentTconst       193 non-null    object
 8   ordering           193 non-null    float64
 9   title_series       193 non-null    object
 10  genres             193 non-null    object
 11  startYear          193 non-null    float64
 12  voisin1            193 non-null    object
 13  voisin2            193 non-null    object
 14  voisin3            193 non-null    object
 15  voisin4            193 non-null    object
dtypes: float64(3), int64(1), object(12)
memory usage: 24.2+ KB